### ISSUE TITLE
Reproducable examples of what and when to call

### ISSUE THREAD

**Issue by asencis** [hex-digital/nuxt-intercom#18]
Could we have reproducable examples of what we can call and when we can call it.

We're running into all sorts of issues with lifecycle hooks and this.$intercom being defined or ready.

We're also seeing window.Intercom is not defined errors.

**Comment by asencis** [comment]
@Jamiewarb Examples we would like would be:

- How to ensure $intercom always boots.
- Fully reproducable example of how to boot and init if autoboot is set to false.
- How to flush out out the userData value on post logout call and return widget back to default state.
- How to ensure post update call doesn't "hide" intercom widget post update.

We also would like to suggest the _flushUserData() call is made public and can be called from anywhere when the user object is flushed in the application.

**Comment by Jamiewarb** [comment]
Hi again asencis,

It sounds like you might be having troubles specific to your application. I mentioned in the previous repo that the best way to get help with that would be to create a reproduction that you can share with me so I can take a look.

As for these examples, I'd point you to the Intercom documentation where it's already covered:

https://developers.intercom.com/installing-intercom/docs/intercom-javascript

I'll try to highlight each of these to help you out.

>How to ensure $intercom always boots.

This sounds like a bug you're having, so it's hard to really give an example of this. I'll combine it with the second point, that talks about how to init and boot intercom.

>Fully reproducable example of how to boot and init if autoboot is set to false.

The `example` directory of this repo shows a fully reproducible example of how to add the plugin and initialise Intercom. The next step is simply to call `this.$intercom.boot(args)` from a clientside hook in a Vue component, or from the context object in the Vuex store. 

As for fully reproducible, the example directory shows a custom plugin, `example/plugin/intercom.js` which is calling the boot method. This runs in the regular plugin lifecycle of Nuxt. 

Where you will need to call boot is dependent on your application. This is why I have recommended creating a reproduction repo so that I can see what problem you're facing in situ.

>How to flush out out the userData value on post logout call and return widget back to default state.

You're looking for Intercom's shutdown method.

https://developers.intercom.com/installing-intercom/docs/intercom-javascript#section-intercomshutdown

You can call it with `this.$intercom.shutdown()`. 

>How to ensure post update call doesn't "hide" intercom widget post update.

This again sounds like a bug you're having in your application, and isn't something that occurs in the example demo. 

For further help with your application, please can you create an example repo that I can clone and take a look at.
