### ISSUE TITLE
Custom Launcher

### ISSUE THREAD

**Issue by josephgu95** [hex-digital/nuxt-intercom#5]
I am trying to use a custom launcher to open the messenger when a button is clicked (https://www.intercom.com/help/en/articles/2894-customize-the-intercom-messenger-technical). I tried inserting custom_launcher_selector:'#my_custom_link' like this inside of nuxt.config.js:

  buildModules: [
    '@hexdigital/nuxt-intercom',
  ],
  intercom: {
    appId: 'XXXXXXXXX',
,   custom_launcher_selector:'#my_custom_link'
  },

However, I couldn't get it to work.

**Comment by Jamiewarb** [comment]
Hi there,

Thanks for opening the issue on this

Looks like this unsupported at the moment. Will look to add it soon, or please open a PR if you’d like to help out ☺️

**Comment by jculverwell** [comment]
Thanks for a great project.  Just in case anyone else needs this there is a workaround where you can just hook into the Intercom api

```
 showIntercom() {
    // @ts-ignore
    window.Intercom("showNewMessage");
  }

**Comment by Jamiewarb** [comment]
Thanks for sharing that!

**Comment by ikbenben** [comment]
@jculverwell thanks for the info, but how did you set this up? 

We don't want the default button in the bottom left to be displayed and so we set the `autoBoot` flag to false. but when we call the `window.Intercom("showNewMessage")` or even the methods added to the Intercom class in this project, then nothing happens. When we navigate to a new page, then it shows..but it is also show the default button at this point.

With the Intercom custom launcher selector option, this is not the expected behaviour. We've implmented this on another non-nuxtjs website. When you use the Intercom option, then when it does open, the default button is not displayed, only the message window. You can see in the screenshot, that the round button is not displayed below the message window.
<img width="424" alt="Screenshot 2021-06-12 at 19 41 04" src="https://user-images.githubusercontent.com/1530664/121784767-23338f00-cbb6-11eb-9c62-a2417328c8fa.png">

I think the `custom_launcher_selector` option puts Intercom into a specific state. Are you working this somehow?
